/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Scala library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.6/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the scala Plugin to add support for Scala.
    scala

    // Apply the java-library plugin for API and implementation separation.
    `java-library`
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use Scala 2.13 in our library project
    implementation(libs.scala.library)
    implementation(libs.logback.classic)
    implementation(libs.scala.logging)

    implementation(libs.typesafe.config)
    implementation(libs.ficus)
    implementation(libs.minio)

    implementation(libs.commons.io)
    implementation(libs.commons.compress)

    // Use Scalatest for testing our library
    testImplementation(libs.scalatest.v2.v13)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}
